name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12, 1.13, 1.14]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s .)
    - name: Run go vet
      run: go vet ./...
    - name: Run go lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: 1.27.0
    - name: Run tests
      run: go test -v ./...
